//Tokens definition
export const OTTO = '${SUBGRAPH_OTTO_ADDRESS}'
export const OTTO_V2_BLOCK = '${SUBGRAPH_OTTO_V2_BLOCK}'
export const OTTO_V3_BLOCK = '${SUBGRAPH_OTTO_V3_BLOCK}'
export const OTTO_V4_BLOCK = '${SUBGRAPH_OTTO_V4_BLOCK}'
export const OTTO_EPOCH_BOOST_BLOCK = '${SUBGRAPH_OTTO_EPOCH_BOOST_BLOCK}'

export const OTTO_ITEM = '${SUBGRAPH_OTTO_ITEM_ADDRESS}'
export const OTTO_RARITY_SCORE_START_ID = '${SUBGRAPH_OTTO_RARITY_SCORE_START_ID}'

export const OTTOPIA_STORE = '${SUBGRAPH_OTTOPIA_STORE_ADDRESS}'

export const OTTOPIA_RARITY_SCORE_RANKING_FIRST_EPOCH = ${SUBGRAPH_OTTOPIA_RARITY_SCORE_RANKING_FIRST_EPOCH}
export const OTTOPIA_RARITY_SCORE_RANKING_DURATION = ${SUBGRAPH_OTTOPIA_RARITY_SCORE_RANKING_DURATION}

export const LATEST_TIMESTAMP = ${SUBGRAPH_LATEST_TIMESTAMP}

export const ADVENTURE = '${SUBGRAPH_ADVENTURE_ADDRESS}'
