//Tokens definition
export const OTTO = '${SUBGRAPH_OTTO_ADDRESS}'
export const OTTO_V2_BLOCK = '${SUBGRAPH_OTTO_V2_BLOCK}'
export const OTTO_V3_BLOCK = '${SUBGRAPH_OTTO_V3_BLOCK}'

export const OTTO_ITEM = '${SUBGRAPH_OTTO_ITEM_ADDRESS}'
export const OTTO_RARITY_SCORE_START_ID = '${SUBGRAPH_OTTO_RARITY_SCORE_START_ID}'

export const OTTOPIA_STORE = '${SUBGRAPH_OTTOPIA_STORE_ADDRESS}'
